spring:
  application:
    name: GroupTaskManagerApi

  jackson:
    property-naming-strategy: SNAKE_CASE

  datasource:
    url: jdbc:postgresql://localhost:5432/taskappdb
    username: taskappuser
    password: password

  flyway:
    enabled: true
    locations: classpath:db/migration

logging:
  level:
    # FIXME
    jp.co.future.uroborosql.sql: TRACE
    jp.co.future.uroborosql.log: DEBUG
    jp.co.future.uroborosql.performance: DEBUG
    org.springframework.jdbc.core: DEBUG
    org.springframework.jdbc.datasource: DEBUG