spring:
  application:
    name: GroupTaskManagerApi

  jackson:
    property-naming-strategy: SNAKE_CASE

  datasource:
    url: jdbc:postgresql://localhost:5432/taskappdb
    username: taskappuser
    password: password